FROM nginx:alpine

RUN apk add --no-cache openssl

COPY nginx.dev.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /docker-entrypoint.d /etc/nginx/ssl

COPY generate-ssl.sh /docker-entrypoint.d/10-generate-ssl.sh

RUN chmod +x /docker-entrypoint.d/10-generate-ssl.sh

EXPOSE 3000 8000

